### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dicorynia** [kuperov/fit#2]
Hi. Thanks for having developed this package, it looks promising...
However the installation fails for me :

    > devtools::install_github('kuperov/fit')
    Downloading GitHub repo kuperov/fit@master
    from URL https://api.github.com/repos/kuperov/fit/zipball/master
    Installing fit
    '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
    '/tmp/Rtmpwwva2z/devtoolsb4be136580/kuperov-fit-210fb91'  \
    --library='/home/user/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 
    
    * installing *source* package ‘fit’ ...
    ** libs
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c fit.cpp -o fit.o
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c fit_accumulated_field.cpp -o fit_accumulated_field.o
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c fit_accumulator.cpp -o fit_accumulator.o
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c fit_buffer_encode.cpp -o fit_buffer_encode.o
    fit_buffer_encode.cpp: In member function ‘std::__cxx11::string fit::BufferEncode::Close()’:
      fit_buffer_encode.cpp:78:57: error: ‘memcpy’ was not declared in this scope
    memcpy((FIT_UINT8 *)&file_header.data_type, ".FIT", 4);
    ^
      /usr/lib/R/etc/Makeconf:168 : la recette pour la cible « fit_buffer_encode.o » a échouée
    make: *** [fit_buffer_encode.o] Erreur 1
    ERROR: compilation failed for package ‘fit’
    * removing ‘/home/user/R/x86_64-pc-linux-gnu-library/3.4/fit’
    Installation failed: Command failed (1)

Any idea ?

> R version 3.4.4 (2018-03-15)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Linux Mint 18.3

```

**Comment by russelldb** [comment]
Does adding a file ~/.R/Makevars
add the following line to that file `CXXFLAGS=-g -std=c++11` do it for you? It's what I had to do to get it to work. I also changed to the latest FIT SdK (because my Garmin 520 FIT files would not work with this package) I have a fork at russelldb/fit, have raised and issue and will open a PR if kuperov wants it.

**Comment by dicorynia** [comment]
Hi
Thanks for the tip. However the error is still here...

    > devtools::install_github('kuperov/fit')
    Downloading GitHub repo kuperov/fit@master
    from URL https://api.github.com/repos/kuperov/fit/zipball/master
    Installing fit
    '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
    '/tmp/RtmpYIYPUR/devtools182eacc675e/kuperov-fit-210fb91' --library='/home/user/R/x86_64-pc-linux-gnu-library/3.4'  \
    --install-tests 
    
    * installing *source* package ‘fit’ ...
    ** libs
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -std=c++11 -c RcppExports.cpp -o RcppExports.o
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -std=c++11 -c fit.cpp -o fit.o
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -std=c++11 -c fit_accumulated_field.cpp -o fit_accumulated_field.o
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -std=c++11 -c fit_accumulator.cpp -o fit_accumulator.o
    g++  -I/usr/share/R/include -DNDEBUG  -I"/home/user/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"    -fpic  -g -std=c++11 -c fit_buffer_encode.cpp -o fit_buffer_encode.o
    fit_buffer_encode.cpp: In member function ‘std::__cxx11::string fit::BufferEncode::Close()’:
      fit_buffer_encode.cpp:78:57: error: ‘memcpy’ was not declared in this scope
    memcpy((FIT_UINT8 *)&file_header.data_type, ".FIT", 4);
    ^
      /usr/lib/R/etc/Makeconf:168 : la recette pour la cible « fit_buffer_encode.o » a échouée
    make: *** [fit_buffer_encode.o] Erreur 1
    ERROR: compilation failed for package ‘fit’
    * removing ‘/home/user/R/x86_64-pc-linux-gnu-library/3.4/fit’
    Installation failed: Command failed (1)

**Comment by smu** [comment]
same error here, with R 3.5.2
